apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "xgboost-iris"
spec:
  default:
    predictor:
      xgboost:
        #storageUri: "http://store04:31888/xgboost/iris"
        storageUri: "/data1/k8s_nfs/models/xgboost/iris"