apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image:  nginx:alpine
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-data
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      volumes:
        - name: nginx-data
          nfs:
            path: /data1/k8s_nfs/models
            server: store03
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31888
      protocol: TCP
  type: NodePort
  selector:
    name: nginx
